#!/usr/bin/env bash

TMPFILE="$(mktemp -t screenlockXXX.png)"
trap "rm -f '$TMPFILE'" 0               # EXIT
trap "rm -f '$TMPFILE'; exit 1" 2       # INT
trap "rm -f '$TMPFILE'; exit 1" 1 15    # HUP TERM

scrot "${TMPFILE}"
# http://www.imagemagick.org/Usage/blur/
gm convert "${TMPFILE}" -blur 5x2 "${TMPFILE}"
i3lock -i "${TMPFILE}"
